// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"cmdDaemon/config"
	"cmdDaemon/daemon"
	"cmdDaemon/register"
	"context"
	"github.com/google/wire"
	"go.uber.org/zap"
	"go.uber.org/zap/zapcore"
	"os/exec"
)

// Injectors from wire.go:

// injector
func createLogger(level zapcore.Level) *zap.SugaredLogger {
	sugaredLogger := NewLogger(level)
	return sugaredLogger
}

func createCmds(conf2 *config.Conf) []*exec.Cmd {
	v := config.GenerateCmds(conf2)
	return v
}

func createDaemon(ctx context.Context, cmds []*exec.Cmd, logger *zap.SugaredLogger) *daemon.Daemon {
	daemonDaemon := daemon.NewDaemon(ctx, cmds, logger)
	return daemonDaemon
}

func createConsul(Consuladdr string, daemon2 *daemon.Daemon, intfList []string, logger *zap.SugaredLogger) (*register.Consul, error) {
	node, err := register.NewNode(intfList)
	if err != nil {
		return nil, err
	}
	v, err := register.NewServiceList(node, daemon2)
	if err != nil {
		return nil, err
	}
	consul, err := register.NewConsul(Consuladdr, node, daemon2, v, logger)
	if err != nil {
		return nil, err
	}
	return consul, nil
}

// wire.go:

// provider
var (
	DaemonSet = wire.NewSet(daemon.NewDaemon, daemon.NewLimiter, daemon.NewDaemonCmd)
	ConsulSet = wire.NewSet(register.NewConsul, register.NewServiceList, register.NewNode)
)
