// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"cmdDaemon/config"
	"cmdDaemon/daemon"
	"cmdDaemon/register"
	"context"
	"github.com/google/wire"
	"go.uber.org/zap"
)

// Injectors from wire.go:

// injector
func createDaemon(ctx context.Context, conf2 *config.Conf) (*daemon.Daemon, error) {
	v := config.GenerateCmds(conf2)
	sugaredLogger := NewLogger()
	daemonDaemon := daemon.NewDaemon(ctx, v, sugaredLogger)
	return daemonDaemon, nil
}

func createConsul(Consuladdr string, daemon2 *daemon.Daemon, logger *zap.SugaredLogger) (*register.Consul, error) {
	node, err := register.NewNode()
	if err != nil {
		return nil, err
	}
	v, err := register.NewServiceList(node, daemon2)
	if err != nil {
		return nil, err
	}
	consul, err := register.NewConsul(Consuladdr, node, daemon2, v, logger)
	if err != nil {
		return nil, err
	}
	return consul, nil
}

// wire.go:

// provider
var (
	DaemonSet = wire.NewSet(daemon.NewDaemon, daemon.NewLimiter, daemon.NewDaemonCmd, NewLogger, config.GenerateCmds)
	ConsulSet = wire.NewSet(register.NewConsul, register.NewServiceList, register.NewNode)
)
