// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "Apache 2.0"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/list": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reload"
                ],
                "summary": "列出所有子进程的端口和命令",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.SvcManagerResponse"
                        }
                    }
                }
            }
        },
        "/reload": {
            "put": {
                "description": "?update 可以选择是否更新配置文件daemon.yml",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reload"
                ],
                "summary": "reload守护进程和子进程",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.SvcManagerResponse"
                        }
                    }
                }
            }
        },
        "/restart": {
            "put": {
                "description": "?update 可以选择是否更新配置文件daemon.yml",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Restart"
                ],
                "summary": "重启daemon进程和所有子进程",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.SvcManagerResponse"
                        }
                    }
                }
            }
        },
        "/stop": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Stop"
                ],
                "summary": "更新配置文件",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.SvcManagerResponse"
                        }
                    }
                }
            }
        },
        "/update": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Update"
                ],
                "summary": "更新配置文件",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.SvcManagerResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handler.SvcManagerResponse": {
            "type": "object",
            "properties": {
                "err": {
                    "type": "string"
                },
                "v": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.5.6",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "守护进程服务",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
